[workspace]
members = [
    "playday",
    "playday_celery_beat",
    "playday_celery_worker",
    "playday_web",
]

[patch.crates-io]
celery = { git = 'https://github.com/rusty-celery/rusty-celery', branch = 'main' }
oauth2 = { git = 'https://github.com/ramosbugs/oauth2-rs', branch = 'main' }
