version: "3.9"  # optional since v1.27.0
services:
  db:
    image: postgres:13.3-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: playday
      POSTGRES_USER: playday
      POSTGRES_DB: playday
