---

- name: reload nginx
  command: docker kill --signal=HUP nginx

- name: restart nginx
  service:
    name: nginx
    state: restarted

- name: restart app
  service:
    name: playday
    state: restarted

- name: reload systemd
  systemd:
    daemon_reload: yes
